spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1083400336538-8qjvvk7n9m5nsg8bl83n1o9apn8h5a27.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          naver:
            client-id: LiPhRLgcaWVyfUTYrGuX
            client-secret: tklQHkM_6n
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        #naver provider가 등록이 되어 있지 않기에, naver provider 등록
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json으로 받는데, response라는 키값으로 네이버가 리턴함
